import Link from 'next/link'

const sections = [
  ['1. Who we are', <><strong>IRIS</strong> is an identity-risk and security-intelligence service operated by MetaPhoenix Tech ("MetaPhoenix", "we", "us", or "our"). This notice explains how we collect, use, disclose, retain, and protect personal information when you visit our website, create an account, submit a scan, or contact us. It is written with reference to applicable data-protection principles in Eswatini, the Southern African Development Community (SADC), the African Union Convention on Cyber Security and Personal Data Protection, and widely recognised global transparency standards including the GDPR. The law that applies to a particular person or processing activity depends on the circumstances; this notice does not replace local legal advice.</>],
  ['2. Information we collect', <><ul><li><strong>Account information:</strong> name, email address, authentication identifiers, and account preferences.</li><li><strong>Scan inputs:</strong> domains, email addresses, phone numbers, and public social-profile URLs that you submit. Do not submit passwords, access tokens, private keys, confidential documents, or information you are not authorised to process.</li><li><strong>Scan outputs:</strong> risk scores, verified findings, public-web observations, source references, remediation guidance, scan status, and timestamps.</li><li><strong>Technical information:</strong> IP address, browser and device details, approximate location derived from IP, logs, error reports, and security events.</li><li><strong>Communications:</strong> messages and information you provide when requesting support or reporting a problem.</li></ul></>],
  ['3. How we use information', <><p>We process information to provide and secure IRIS, authenticate users, run requested passive checks, generate evidence reports, show scan history, provide remediation guidance, prevent abuse, investigate incidents, improve reliability, respond to support requests, comply with legal obligations, and protect the rights and safety of users and third parties. We do not use submitted credentials to access accounts or systems, and we do not perform intrusive testing, password guessing, or bypass privacy controls.</p></>],
  ['4. Lawful grounds and consent', <><p>Depending on the jurisdiction and context, our grounds may include performance of a contract with you, steps taken at your request before a contract, compliance with a legal obligation, our legitimate interests in operating and securing the service, and your consent where consent is required. Where processing relies on consent, you may withdraw it at any time; withdrawal does not affect processing already carried out lawfully.</p></>],
  ['5. Public profiles and third-party sources', <><p>When you submit a public social-profile URL, IRIS may review publicly accessible pages and search results to produce bounded, source-backed observations. We do not request or use private-profile access, login credentials, or methods intended to defeat access controls. A profile that is private, blocked, not indexed, or unavailable may produce limited results; absence of a finding is not a guarantee of safety. Third-party pages have their own privacy policies and may receive technical requests when accessed.</p></>],
  ['6. Sharing and processors', <><p>We may share information with carefully selected service providers that host infrastructure, database, authentication, security monitoring, analytics, email, or AI-assisted processing on our instructions. They may process information only for the agreed service and must apply appropriate confidentiality and security obligations. We may disclose information where required by law, court order, regulator, or lawful government request, or where necessary to protect users, the service, or the public. We do not sell personal information.</p></>],
  ['7. International transfers', <><p>Our providers or infrastructure may process information outside Eswatini or your country. Before a restricted transfer, we seek an appropriate legal mechanism and safeguards recognised by applicable law, which may include an adequacy decision, approved contractual safeguards, consent, contractual necessity, or another permitted exception. SADC and African data-protection requirements may also apply to regional transfers. You may contact us for information about the safeguards relevant to your request.</p></>],
  ['8. Retention', <><p>We retain account and scan information only for as long as reasonably necessary for the purposes described here, including providing history, resolving disputes, enforcing terms, maintaining security records, and meeting legal obligations. Retention varies by data type and risk. When information is no longer required, we delete it, anonymise it, or securely isolate it where deletion is not immediately possible.</p></>],
  ['9. Security and breach response', <><p>We use access controls, least-privilege permissions, encryption in transit, service monitoring, validation, and secure operational practices appropriate to the risk. No online service is completely secure. If a personal-data breach is likely to create a risk to individuals, we will assess, contain, document, and notify the relevant authority and affected people where required by applicable law. In Eswatini, this includes the statutory breach-notification framework and applicable EDPA requirements.</p></>],
  ['10. Your rights', <><p>Subject to applicable law and lawful exceptions, you may request access to your information, correction of inaccurate information, deletion, restriction, objection to certain processing, portability where applicable, and withdrawal of consent. You may also complain to the competent supervisory authority, including the Eswatini Data Protection Authority where it has jurisdiction. We may need to verify your identity and may explain when a request cannot be fulfilled.</p></>],
  ['11. Children', <><p>IRIS is not directed to children who cannot lawfully consent to the processing of their information. If you believe a child has provided personal information improperly, contact us so we can investigate and take appropriate action.</p></>],
  ['12. Cookies and similar technologies', <><p>We may use essential cookies or comparable technologies for authentication, security, session continuity, and basic preferences. Non-essential analytics or marketing technologies will be used only where permitted and, where required, after consent. Browser controls may affect functionality.</p></>],
  ['13. Changes and contact', <><p>We may update this notice when the service, law, or processing changes. The effective date below identifies the current version. For access, deletion, correction, privacy questions, or complaints, contact MetaPhoenix Tech through the support contact published in the IRIS application. Please do not include passwords, tokens, or other secrets in your message.</p></>],
]

export default function PrivacyPage() {
  return <main className="min-h-screen bg-[var(--iris-white)] px-6 py-12 text-[var(--iris-ink)] sm:py-20"><article className="mx-auto max-w-4xl"><Link href="/" className="font-black tracking-[0.24em] text-[var(--iris-navy)]">IRIS</Link><header className="mt-12 border-b border-[var(--iris-line)] pb-10"><p className="iris-kicker">Trust centre</p><h1 className="mt-3 text-4xl font-black tracking-[-0.04em] text-[var(--iris-navy)] sm:text-6xl">Privacy notice</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-[var(--iris-muted)]">A plain-language explanation of how IRIS handles information, evidence, and public-web research.</p><p className="mt-5 text-sm font-bold text-[var(--iris-muted)]">Effective date: 9 September 2026 · Version 1.0</p></header><div className="mt-10 flex flex-col gap-10">{sections.map(([title, body]) => <section key={title as string} className="border-b border-[var(--iris-line)] pb-9"><h2 className="text-xl font-black text-[var(--iris-navy)]">{title}</h2><div className="mt-4 space-y-4 leading-8 text-slate-700">{body}</div></section>)}</div><Link href="/" className="mt-10 inline-block font-bold text-blue-700 hover:underline">Return to IRIS</Link></article></main>
}
