'use client'

import { FormEvent, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { createSupabaseBrowserClient } from '@/lib/supabase-browser'

export default function SignUpPage() {
  const router = useRouter(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [loading, setLoading] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(null); setMessage(null); const { error } = await createSupabaseBrowserClient().auth.signUp({ email, password, options: { emailRedirectTo: `${window.location.origin}/auth/callback` } }); setLoading(false); if (error) { setError(error.message.includes('weak') ? 'Choose a stronger password.' : 'Unable to create your account. Please try again.'); return } setMessage('Check your inbox to confirm your email, then sign in.'); router.replace('/auth/sign-up-success') }
  return <main className="mx-auto flex min-h-screen max-w-md items-center px-6 py-16"><section className="w-full rounded-2xl border border-slate-800 bg-slate-950/70 p-8"><p className="font-mono text-xs uppercase tracking-[0.25em] text-amber-400">IRIS / workspace</p><h1 className="mt-5 text-3xl font-semibold">Create your account</h1><p className="mt-3 leading-7 text-slate-400">Keep scan history private and return to remediation work whenever you need.</p><form onSubmit={submit} className="mt-8 flex flex-col gap-5"><label className="flex flex-col gap-2 text-sm text-slate-300">Email<input className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-3 outline-none focus:border-amber-400" type="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label className="flex flex-col gap-2 text-sm text-slate-300">Password<input className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-3 outline-none focus:border-amber-400" type="password" minLength={8} value={password} onChange={e => setPassword(e.target.value)} required /></label>{error && <p role="alert" className="text-sm text-rose-300">{error}</p>}{message && <p role="status" className="text-sm text-emerald-300">{message}</p>}<button disabled={loading} className="rounded-lg bg-amber-400 px-4 py-3 font-semibold text-slate-950 disabled:opacity-50">{loading ? 'Creating…' : 'Create account'}</button></form><p className="mt-6 text-sm text-slate-400">Already have an account? <Link className="text-amber-300 underline" href="/auth/login">Sign in</Link></p></section></main>
}
