import Link from 'next/link'

const sections = [
  ['1. Agreement and eligibility', <><p>These Terms of Use form an agreement between you and MetaPhoenix Tech ("MetaPhoenix", "we", "us", or "our") for your use of IRIS. By creating an account, submitting a scan, or using the service, you confirm that you have authority to accept these Terms and will comply with applicable law. If you use IRIS for an organisation, you represent that you are authorised to bind it.</p></>],
  ['2. What IRIS does', <><p>IRIS provides identity-risk and security-intelligence observations based on information you submit and, where relevant, publicly accessible sources. It can return risk scores, findings, source references, profile summaries, and remediation guidance. Results are probabilistic and time-sensitive. They are not a guarantee, certification, audit opinion, legal opinion, employment decision, credit decision, identity verification, or substitute for professional security, privacy, legal, or compliance advice.</p></>],
  ['3. Authorised use only', <><p>You may submit only domains, addresses, phone numbers, profiles, and other targets that you own or are authorised to assess. You must not use IRIS to stalk, harass, dox, discriminate against, impersonate, surveil, or make high-impact decisions about another person without a lawful basis and appropriate safeguards. You must not submit passwords, access tokens, private keys, payment-card data, confidential documents, or data obtained unlawfully.</p></>],
  ['4. Prohibited technical activity', <><p>You must not use IRIS to probe, exploit, disrupt, overload, bypass authentication, defeat privacy settings, evade rate limits, reverse engineer protected systems, upload malware, test unauthorised targets, or interfere with another person’s service. You must not scrape IRIS, extract results at scale, or use automated access except through documented interfaces we expressly provide.</p></>],
  ['5. Public-web research', <><p>Some social-profile scans inspect public pages and search results only. IRIS does not request your social-media password, access private profiles, or bypass a login wall. A private, blocked, deleted, or unindexed page may return limited evidence. Public information may be inaccurate, stale, incomplete, or attributed incorrectly; you are responsible for reviewing sources before acting.</p></>],
  ['6. Accounts and security', <><p>You are responsible for keeping account credentials confidential, using a strong unique password, and notifying us promptly of suspected unauthorised access. You are responsible for activity performed through your account unless caused by our breach of reasonable security obligations. We may suspend access to protect the service, users, or third parties.</p></>],
  ['7. Results and responsible decisions', <><p>Do not rely on an IRIS score or finding as the sole basis for a decision that could materially affect a person’s rights, opportunities, access to services, employment, housing, education, insurance, or credit. Verify important results independently, provide appropriate notice and review, and follow data-protection, anti-discrimination, consumer-protection, and sector-specific rules.</p></>],
  ['8. Intellectual property', <><p>IRIS, its software, design, documentation, branding, and original content are owned by or licensed to MetaPhoenix and protected by applicable intellectual-property law. We grant you a limited, non-exclusive, non-transferable right to use the service for its intended purpose. You retain rights in information you submit, while granting us the limited rights needed to operate the service and produce your requested results.</p></>],
  ['9. Acceptable feedback and content', <><p>You must not submit content that is unlawful, defamatory, invasive of privacy, infringing, malicious, or misleading. You grant us permission to host and process submitted content only as necessary to provide, secure, support, and improve IRIS, subject to the Privacy Notice. We may remove content or restrict access where reasonably necessary.</p></>],
  ['10. Availability and third parties', <><p>We aim to provide a reliable service but do not promise uninterrupted availability, a particular scan speed, or that every source will be reachable. IRIS may depend on third-party hosting, authentication, search, data, and AI services. Those services may change or fail, and their own terms may apply. We are not responsible for third-party content or decisions made using it.</p></>],
  ['11. Fees and changes', <><p>If paid features are introduced, pricing, taxes, renewal, cancellation, and refund terms will be shown before purchase. We may modify features, limits, or these Terms to reflect service or legal changes. We will provide notice where required. Continued use after the effective date means you accept the updated Terms; if you disagree, stop using the service.</p></>],
  ['12. Suspension and termination', <><p>You may stop using IRIS at any time. We may suspend or terminate access for breach, unlawful use, security risk, non-payment, or operational reasons, subject to applicable law. Provisions concerning ownership, confidentiality, limitations, dispute resolution, and accrued obligations survive termination.</p></>],
  ['13. Disclaimers', <><p>To the maximum extent permitted by law, IRIS is provided on an “as available” and “as is” basis. We disclaim implied warranties that cannot lawfully be excluded, including uninterrupted availability, complete accuracy, fitness for a particular purpose, and non-infringement. Nothing in these Terms excludes a consumer or other statutory right that cannot lawfully be excluded.</p></>],
  ['14. Liability', <><p>To the maximum extent permitted by applicable law, MetaPhoenix will not be liable for indirect, incidental, special, consequential, exemplary, or punitive loss, loss of profits, data, goodwill, or business interruption arising from use of the service. Our aggregate liability for a claim relating to IRIS will not exceed the amount you paid us for the service during the twelve months before the event giving rise to the claim, except where a different limit is prohibited by law.</p></>],
  ['15. Law and disputes', <><p>These Terms are interpreted subject to the mandatory laws that protect you in your place of residence. Where permitted, disputes should first be raised with us in writing so the parties can attempt good-faith resolution. Nothing prevents you from contacting a competent regulator, pursuing a statutory consumer remedy, or seeking urgent relief from a court with jurisdiction. We will not contract out of mandatory protections under applicable Eswatini, SADC, African Union, or other law.</p></>],
  ['16. Contact', <><p>Questions about these Terms, suspected misuse, or legal notices should be sent through the support contact published in the IRIS application. Do not send passwords, private keys, access tokens, or other secrets. This version is effective 9 September 2026.</p></>],
]

export default function TermsPage() {
  return <main className="min-h-screen bg-[var(--iris-white)] px-6 py-12 text-[var(--iris-ink)] sm:py-20"><article className="mx-auto max-w-4xl"><Link href="/" className="font-black tracking-[0.24em] text-[var(--iris-navy)]">IRIS</Link><header className="mt-12 border-b border-[var(--iris-line)] pb-10"><p className="iris-kicker">Trust centre</p><h1 className="mt-3 text-4xl font-black tracking-[-0.04em] text-[var(--iris-navy)] sm:text-6xl">Terms of use</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-[var(--iris-muted)]">The rules for using IRIS responsibly, lawfully, and with respect for people whose information may appear in public sources.</p><p className="mt-5 text-sm font-bold text-[var(--iris-muted)]">Effective date: 9 September 2026 · Version 1.0</p></header><div className="mt-10 flex flex-col gap-10">{sections.map(([title, body]) => <section key={title as string} className="border-b border-[var(--iris-line)] pb-9"><h2 className="text-xl font-black text-[var(--iris-navy)]">{title}</h2><div className="mt-4 space-y-4 leading-8 text-slate-700">{body}</div></section>)}</div><Link href="/" className="mt-10 inline-block font-bold text-blue-700 hover:underline">Return to IRIS</Link></article></main>
}
