import Link from 'next/link'
import { redirect } from 'next/navigation'
import { createSupabaseServerClient } from '@/lib/supabase-server'

export default async function DashboardPage() {
  const supabase = await createSupabaseServerClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/auth/login?next=/dashboard')
  const { data: scans } = await supabase.from('scans').select('id, domain, target_type, target_platform, status, risk_score, created_at').eq('owner_id', user.id).order('created_at', { ascending: false }).limit(12)
  const recentScans = (scans ?? []) as Array<{ id: string; domain: string | null; target_type: string; target_platform: string | null; status: string; risk_score: number | null; created_at: string }>
  return <main className="min-h-screen bg-[var(--iris-white)]"><header className="border-b bg-white/90"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><Link href="/" className="flex items-center gap-3"><img src="/iris-logo.png" alt="IRIS" className="h-10 w-10 rounded-xl" /><span className="font-mono text-sm font-bold tracking-[0.22em] text-[var(--iris-navy)]">IRIS</span></Link><div className="flex items-center gap-3"><Link href="/" className="hidden rounded-xl bg-[var(--iris-blue)] px-4 py-2.5 text-sm font-bold text-white sm:block">New scan</Link><a href="/auth/sign-out" className="rounded-xl border px-4 py-2.5 text-sm font-bold text-[var(--iris-navy)] hover:border-[var(--iris-blue)]">Sign out</a></div></div></header><div className="mx-auto max-w-6xl px-6 py-12"><div className="max-w-2xl"><p className="iris-kicker">Personal security workspace</p><h1 className="mt-3 text-4xl font-bold tracking-tight text-[var(--iris-navy)]">Your posture, in progress.</h1><p className="mt-4 leading-7 text-[var(--iris-muted)]">Private scan history, verified findings, and remediation guides in one calm place.</p></div><section className="iris-panel mt-10 overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b px-6 py-5"><div><h2 className="font-bold text-[var(--iris-navy)]">Recent scans</h2><p className="mt-1 text-sm text-[var(--iris-muted)]">Only scans associated with your account appear here.</p></div><Link href="/" className="text-sm font-bold text-[var(--iris-blue)]">Run another scan</Link></div>{recentScans.length ? <div className="divide-y">{recentScans.map(scan => <Link key={scan.id} href={`/scan/${scan.id}`} className="flex flex-wrap items-center justify-between gap-4 px-6 py-5 transition hover:bg-blue-50/50"><div><p className="font-semibold capitalize text-[var(--iris-navy)]">{scan.target_type.replace('_', ' ')}{scan.target_platform ? ` · ${scan.target_platform}` : ''}</p><p className="mt-1 text-sm text-[var(--iris-muted)]">{scan.domain ?? 'Privacy-protected target'} · {new Date(scan.created_at).toLocaleDateString()}</p></div><div className="flex items-center gap-4 text-sm"><span className="capitalize text-[var(--iris-muted)]">{scan.status}</span>{scan.risk_score !== null && <span className="rounded-full bg-blue-50 px-3 py-1 font-mono font-bold text-[var(--iris-blue)]">{scan.risk_score}/100</span>}</div></Link>)}</div> : <div className="px-6 py-16 text-center"><p className="font-semibold text-[var(--iris-navy)]">Your private history starts here.</p><p className="mt-2 text-sm text-[var(--iris-muted)]">Run an extended scan to save a verified report to this workspace.</p><Link href="/" className="mt-6 inline-flex rounded-xl bg-[var(--iris-blue)] px-4 py-3 font-bold text-white">Start a scan</Link></div>}</section></div></main>
}
